Lowercase variables

diff --git a/nftables-apply b/nftables-apply
--- a/nftables-apply
+++ b/nftables-apply
@@ -27,7 +27,7 @@ fi
 
 # Define constants
 PROGNAME="${0##*/}"
-VERSION='1.2.2'
+VERSION='1.2.3'
 RED="$(tput setaf 1)"
 NC="$(tput sgr0)" # No Color
 
@@ -68,15 +68,15 @@ do
             help
             ;;
         -s|--source-file)
-            export SOURCE_FILE="${2}"
+            export source_file="${2}"
             shift # consume -s
             ;;
         -d|--destination-file)
-            export DESTINATION_FILE="${2}"
+            export destination_file="${2}"
             shift # consume -d
             ;;
         -t|--timeout)
-            export TIMEOUT="${2}"
+            export timeout="${2}"
             shift # consume -t
             ;;
         -V|--version)
@@ -89,9 +89,9 @@ do
 done
 
 # Set defaults if no options specified
-SOURCE_FILE="${SOURCE_FILE:-$DEFAULT_SOURCE_FILE}"
-DESTINATION_FILE="${DESTINATION_FILE:-$DEFAULT_DESTINATION_FILE}"
-TIMEOUT="${TIMEOUT:-$DEFAULT_TIMEOUT}"
+source_file="${source_file:-$DEFAULT_SOURCE_FILE}"
+destination_file="${destination_file:-$DEFAULT_DESTINATION_FILE}"
+timeout="${timeout:-$DEFAULT_TIMEOUT}"
 
 # Change directory to base script directory
 cd "$(dirname "${0}")"
@@ -123,7 +123,7 @@ restore() {
 }
 
 save() {
-    cp "${SOURCE_FILE}" "${DESTINATION_FILE}"
+    cp "${source_file}" "${destination_file}"
     echo -e "\nConfiguration changed"
 
     return 0
@@ -135,9 +135,9 @@ main() {
     check_root
 
     # Check if we can read the destination file
-    if [[ ! -r "${DESTINATION_FILE}" ]]
+    if [[ ! -r "${destination_file}" ]]
     then
-        echo -e "${RED}E:${NC} cannot read ${DESTINATION_FILE}" >&2
+        echo -e "${RED}E:${NC} cannot read ${destination_file}" >&2
         exit 4
     fi
 
@@ -145,19 +145,19 @@ main() {
     nft list ruleset > /tmp/nftables.conf.bak
 
     # Check if we can read the source file
-    if [[ ! -r "${SOURCE_FILE}" ]]
+    if [[ ! -r "${source_file}" ]]
     then
-        echo -e "${RED}E:${NC} cannot read ${SOURCE_FILE}" >&2
+        echo -e "${RED}E:${NC} cannot read ${source_file}" >&2
         exit 5
     fi
 
     # Dry run new ruleset, exit if failures
-    nft -f "${SOURCE_FILE}" || (echo -e "${RED}E:${NC} Invalid rules, exiting" >&2 && exit 6)
+    nft -f "${source_file}" || (echo -e "${RED}E:${NC} Invalid rules, exiting" >&2 && exit 6)
 
     # Check the candidate configuration starts by flushing ruleset
     if [[ $(head -n 1 /etc/nftables-candidate.conf) != "flush ruleset" ]]
     then
-        sed -i '1s/^/flush ruleset\n/' "${SOURCE_FILE}"
+        sed -i '1s/^/flush ruleset\n/' "${source_file}"
     fi
 
     # Stop fail2ban
@@ -167,14 +167,14 @@ main() {
     fi
 
     # Apply new ruleset, rollback if timeout
-    timeout "${TIMEOUT}"s nft -f "${SOURCE_FILE}" || (echo -e "${RED}E:${NC} timeout while applying new configuration, rolling back to the previous ruleset" >&2 && restore && exit 7)
+    timeout "${timeout}"s nft -f "${source_file}" || (echo -e "${RED}E:${NC} timeout while applying new configuration, rolling back to the previous ruleset" >&2 && restore && exit 7)
 
     # Ask the user if they can open a new connection
     # If they can't, rollback
     # If they can, save
     echo -n "Can you establish NEW connections to the machine? (y/N) "
-    read -r -n1 -t "${TIMEOUT}" ANSWER 2>&1 || :
-    if [[ "${ANSWER}" == "y" ]]
+    read -r -n1 -t "${timeout}" answer 2>&1 || :
+    if [[ "${answer}" == "y" ]]
     then
         save
     else
