Header more clear

diff --git a/nftables-apply b/nftables-apply
--- a/nftables-apply
+++ b/nftables-apply
@@ -14,13 +14,11 @@
 # Free adaptation for nftables of iptables-apply (https://github.com/wertarbyte/iptables/blob/master/iptables-apply)
 #
 
+# -e: When a command fails, bash exits instead of continuing with the rest of the script
+# -u: This will make the script fail, when accessing an unset variable
+# -o pipefail: This will ensure that a pipeline command is treated as failed, even if one command in the pipeline fails
+set -euo pipefail
 
-# When a command fails, bash exits instead of continuing with the rest of the script
-set -o errexit
-# This will make the script fail, when accessing an unset variable
-set -o nounset
-# This will ensure that a pipeline command is treated as failed, even if one command in the pipeline fails
-set -o pipefail
 # Enable debug mode by running your script as TRACE=1 ./script.sh instead of ./script.sh
 if [[ "${TRACE-0}" == "1" ]]
 then
@@ -28,7 +26,7 @@ then
 fi
 
 readonly PROGNAME="${0##*/}"
-readonly VERSION="1.1.5"
+readonly VERSION="1.1.6"
 
 readonly DEFAULT_TIMEOUT=15
 readonly DEFAULT_DESTINATION_FILE=/etc/nftables.conf
